export const TYPE_AGREGAR_MATERIAL = 1;
export const TYPE_EDITAR_MATERIAL = 2;
export const TYPE_ELIMINAR_MATERIAL = 3;

export const TYPE_AGREGAR_CATEGORIA = 1;
export const TYPE_EDITAR_CATEGORIA = 2;
export const TYPE_ELIMINAR_CATEGORIA = 3;

export const TYPE_AGREGAR_PROVEEDOR = 1;
export const TYPE_EDITAR_PROVEEDOR = 2;
export const TYPE_ELIMINAR_PROVEEDOR = 3;
